name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      GitHub Actions는 리포지토리의 코드를 자동으로 복사해 오지 않습니다.
#      워크플로 안에서 파일을 읽거나 빌드하려면, 먼저 코드가 runner에 있어야 하므로
#      GitHub 레포지토리의 코드를 runner 머신(Ubuntu 등) 에 복제(clone)합니다.
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test
